apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-keycloak
  namespace: monitoring
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  source:
    repoURL: https://github.com/dohyun-99/app-of-apps-keycloak.git
    targetRevision: HEAD
    path: charts/frontend
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
    
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=false   
